language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.6"

env:
  - PIP_DOWNLOAD_CACHE=$HOME/.pip_download_cache

cache:
  apt: true
  directories:
    - /home/travis/virtualenv/python2.7/lib/python2.7/site-packages
    - /home/travis/virtualenv/python3.4/lib/python3.4/site-packages
    - /home/travis/virtualenv/python3.6/lib/python3.6/site-packages

script:
  - python -m nose --verbose --tests=tests --no-byte-compile --with-coverage --cover-package=omnia --cover-min-percentage=90
  - python -m pylint omnia --rcfile=.pylintrc -r y
