language: python

sudo: false

python:
  - "2.7"
  - "3.5"

env:
  - PIP_DOWNLOAD_CACHE=$HOME/.pip_download_cache

cache:
  apt: true
  directories:
    - /home/travis/virtualenv/python2.7/lib/python2.7/site-packages

install:
  - easy_install -U pip==1.5
  - pip install -Ur requirements.txt

script:
  - ./run_tests.sh
